[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "barrister2"
version = "0.1.0"
description = "Barrister Python Runtime Library"
requires-python = ">=3.7"

